dist: release
source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Tag }}-source'
checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}-checksums.txt'
builds:
  -
    binary: luet-{{ .Tag }}-{{ .Os }}-{{ .Arch }}
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X "github.com/mudler/luet/cmd.BuildTime={{ time "2006-01-02 15:04:05 MST" }}"
      - -X "github.com/mudler/luet/cmd.BuildCommit={{ .FullCommit }}"
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7
    no_unique_dist_dir: true  # dump all the binaries under the dist dir directly instead of subdirs for each
archives:
  - format: binary # this removes the tar of the archives, leaving the binaries alone
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'
release:
  