on:
  workflow_dispatch:
  pull_request:
concurrency:
  group: ci-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
name: Build and release on push
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [ "1.16.x" ]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
