on:
  workflow_dispatch:
  pull_request:
concurrency:
  group: ci-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
name: Build and release on push
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [ "1.16.x" ]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install deps
        run: |
            sudo apt-get install -y upx && sudo -E env "PATH=$PATH" make deps
            sudo curl -fSL "https://github.com/genuinetools/img/releases/download/v0.5.11/img-linux-amd64" -o "/usr/bin/img"
            sudo chmod a+x "/usr/bin/img"
      - name: Build
        run: sudo -E env "PATH=$PATH" make multiarch-build-small
